### ISSUE TITLE
It should not be possible to merge PR when build fails.

### ISSUE THREAD

**Issue by SzymonSmykala** [KSIUJ/ksicamp-the-game#11]
Jenkins tutorial:
https://medium.com/@lfcgomes/testing-your-pull-requests-with-jenkins-b9a290431611

**Comment by apardyl** [comment]
1. @SzymonSmykala jaki jenkins, travisa mamy
2. ktoś musi przynajmniej jednego PR zrobić żeby github ogarnął, że ma travisa podpiętego

**Comment by apardyl** [comment]
a w sumie to przypał z travisem jak repo stało sie prywatne

**Comment by phoe** [comment]
https://origin.ksi.ii.uj.edu.pl/jenkins/

jak coś, to mam jednego na zbyciu

**Comment by apardyl** [comment]
włączyłem branch protection dla mastera
