### ISSUE TITLE
KSIcamp5 - review

### ISSUE THREAD

**Issue by phoe** [KSIUJ/ksicamp-the-game#16]
* połączyć windy tylne z parterem i windami górnymi
* poprawić gramatykę w bibliotece (DONE)
* Windy tylne: poprawić drukowanie przejścia do garażu (DONE)
* garaż: dodać Dziekanowi się nie odmawia
* windy: dodać naprawianie windy za pomocą młotka z serwerowni

**Comment by seqre** [comment]
1 chyba done, bo ogólnie przejście jest zaimplementowane, tylko minigierki brak
