### ISSUE TITLE
Mapa wydziału

### ISSUE THREAD

**Issue by phoe** [KSIUJ/ksicamp-the-game#2]
![](https://cdn.discordapp.com/attachments/375703363893067776/505692210898141205/JPEG_20181027_123953.jpg)

**Comment by LuthaMG** [comment]
Cóż za arcydzieło, nieznany artysta, osiągnie miliony

**Comment by phoe** [comment]
![](https://cdn.discordapp.com/attachments/375703363893067776/505713791225561089/JPEG_20181027_125521.jpg)

**Comment by LuthaMG** [comment]
![1540827956584](https://user-images.githubusercontent.com/25556989/47661862-c7956e00-db91-11e8-9421-5427da13e7e6.jpg)
Bettah wersja by me

**Comment by phoe** [comment]
Beautiful <3

Dnia 29 października 2018 16:50:14 CET, LuthaMG <notifications@github.com> napisał(a):
>![1540827956584](https://user-images.githubusercontent.com/25556989/47661862-c7956e00-db91-11e8-9421-5427da13e7e6.jpg)
>Bettah wersja by me
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phoe-trash/ksicamp-the-game/issues/2#issuecomment-433962300

-- Wysłane za pomocą K-9 Mail.

**Comment by LuthaMG** [comment]
![1540896726297](https://user-images.githubusercontent.com/25556989/47713296-ddf30680-dc31-11e8-9dd3-a493df6f005f.jpg)
New, bettah one
