### ISSUE TITLE
Plan wydziału wymaga dopracowania

### ISSUE THREAD

**Issue by mateuszgwozdz** [KSIUJ/ksicamp-the-game#21]
Jest kilka drobnostek, które wypada wyjaśnić.
Np. Pokój nad którym pracuje @skypio wcale nie wymaga przejścia przez windę, a na parterze też jest korytarz. (sic!)
Proponuję, by na następnym KSICampie dopracować mapę.
@seqre świetnie rozrysował koncept który mieliśmy jakiś czas temu (patrz: [Wiki](https://github.com/KSIUJ/ksicamp-the-game/wiki)),
ale myślę, że przydałaby się jej mała aktualizacja.

**Comment by seqre** [comment]
Pamiętaj, że choć korytarz nazywa się korytarz, to w zamyśle, był tylko tym kawałkiem od głównego do pokoju KSI
