### ISSUE TITLE
Pomysły na fabułę

### ISSUE THREAD

**Issue by phoe** [KSIUJ/ksicamp-the-game#3]
* karta do serwerowni - młotek w niej
* zwój przywołujący marchewkę
* woda budząca żula śpiącego w KSI

**Comment by mateuszgwozdz** [comment]
Randomowy event - nawiedza Cię ultra-rare zając X, napisz Y w ciągu Z sekund, lub zginiesz

**Comment by seqre** [comment]
Jako ten, który implementuje użycie młotka proszę o zamianię (dodanie jako druga znajdźka?) go na śrubokręt, ma on większą rację bytu przy naprawie windy u mnie

**Comment by skypio** [comment]
Misie, kilka informacji ode mnie. W sekretariacie będzie można uzyskać właśnoręcznie podpisany przez Lembasa egzemplarz "Wstępu do informatyki" o nazwie "podrecznik_wdi" oraz kontrowersyjne zdjęcie Kawy "zdjecie_kawa". Jeśli ktoś ma pomysł jak to dalej wykorzystać, to make use of it.  Myślałem jeszcze żeby pobrać w sekretariacie wniosek o zmiane grupy ćwiczeniowej i trzeba będzie uzyskać podpis Kawy i Szufy, których można by ukryć gdzieś na wydziale. Gdzieś może jakby miało się ostatecznie w inventrzu "podpis_kawa" "podpis_szufa" oraz  wspomniany wcześniej "wniosek" coś mogłoby się dziać. Może to przesadzony pomysł, jak macie jakieś myśli to piszcie, jak nie, to ta część umrze.

**Comment by phoe** [comment]
Pamiętajcie, że to repo jest publiczne. (; Może już czas, by je ukryć.

Dnia 7 listopada 2018 11:34:36 CET, "Piotr Skibiński" <notifications@github.com> napisał(a):
>Misie, kilka informacji ode mnie. W sekretariacie będzie można uzyskać
>właśnoręcznie podpisany przez Lembasa egzemplarz "Wstępu do
>informatyki" o nazwie "podrecznik_wdi" oraz kontrowersyjne zdjęcie Kawy
>"zdjecie_kawa". Jeśli ktoś ma pomysł jak to dalej wykorzystać, to make
>use of it.  Myślałem jeszcze żeby pobrać w sekretariacie wniosek o
>zmiane grupy ćwiczeniowej i trzeba będzie uzyskać podpis Kawy i Szufy,
>których można by ukryć gdzieś na wydziale. Gdzieś może jakby miało się
>ostatecznie w inventrzu "podpis_kawa" "podpis_szufa" oraz  wspomniany
>wcześniej "wniosek" coś mogłoby się dziać. Może to przesadzony pomysł,
>jak macie jakieś myśli to piszcie, jak nie, to ta część umrze. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/KSIUJ/ksicamp-the-game/issues/3#issuecomment-436579699

-- Wysłane za pomocą K-9 Mail.

**Comment by skypio** [comment]
ups... dobry pomysł

**Comment by phoe** [comment]
@apardyl pls

Dnia 7 listopada 2018 12:52:16 CET, skypio <notifications@github.com> napisał(a):
>ups... dobry pomysł 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/KSIUJ/ksicamp-the-game/issues/3#issuecomment-436599096

-- Wysłane za pomocą K-9 Mail.

**Comment by apardyl** [comment]
> @apardyl pls 

Wyczyściłem `kontrowersyjny` post i jego następstwa.
