### ISSUE TITLE
Problem z polskimi znakami w g++ 8.1 (MinGW Distro)

### ISSUE THREAD

**Issue by polarny** [KSIUJ/ksicamp-the-game#4]
Miałem wcześniej pewne dziwne problemy podczas działania kodu (wywalał się na jednym z cin'ów), więc zmieniłem kompilator na ten dostarczony przez MinGW Distro (https://nuwen.net/mingw.html). Teraz wszystko działa spoko, ale za to stringi wyglądają w ten sposób. 
"Obudzi┼ée┼¢ si─Ö.
Jeste┼¢ w KSI. S┼éo┼äce zasz┼éo dawno temu. Co┼¢ musia┼éo p├│j┼¢─ç bardzo nie tak.
Obok ciebie le┼╝─à kawa┼éki niedojedzonej pizzy."

Wie ktoś może co z takim fantem należałoby zrobić?

**Comment by phoe** [comment]
Spróbuj `-finput-charset=UTF-8`

Dnia 29 października 2018 19:08:46 CET, polarny <notifications@github.com> napisał(a):
>Miałem wcześniej pewne dziwne problemy podczas działania kodu (wywalał
>się na jednym z cin'ów), więc zmieniłem kompilator na ten dostarczony
>przez MinGW Distro (https://nuwen.net/mingw.html). Teraz wszystko
>działa spoko, ale za to stringi wyglądają w ten sposób. >
>"Obudzi┼ée┼¢ si─Ö.>
>Jeste┼¢ w KSI. S┼éo┼äce zasz┼éo dawno temu. Co┼¢ musia┼éo p├│j┼¢─ç
>bardzo nie tak.>
>Obok ciebie le┼╝─à kawa┼éki niedojedzonej pizzy.">
>>
>Wie ktoś może co z takim fantem należałoby zrobić? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/phoe-trash/ksicamp-the-game/issues/4

-- Wysłane za pomocą K-9 Mail.

**Comment by polarny** [comment]
Rozumiem, że dodać tą flagę do kompilacji tak?
"g++ --std=c++11 -g -Wall -D_GLIBCXX_DEBUG -finput-charset=UTF-8 -o ksicamp-the-game main.cpp util.cpp rooms/*.cpp"
Niestety nic nie pomogło. :(

**Comment by polarny** [comment]
OK, udało mi się ten problem obejść kompilując i odpalając pod "Bash on Ubuntu on Windows" (zamiast w standardowej konsoli CMD bądź PowerShellu). To z kolei g++ 5.4 XD

Nie jest to rozwiązanie idealne, ale chwilowo "whatever works". Nie wywala się też na niczym innym, więc super.
