### ISSUE TITLE
Nawigacja w korytarzu.

### ISSUE THREAD

**Issue by polarny** [KSIUJ/ksicamp-the-game#5]
Nie miałem dużo czasu w ten weekend popracować nad tym, tak więc chwilowo, żeby gdzieś przejść trzeba wpisać nazwę pokoju takimi samymi literami (tj. dużymi/małymi) jak są na ekranie.

Nie zdarzyłem tego zrobić "case-insensitive" (był z tym mały problem) więc na razie wrzucam tak jak jest, żeby brak nawigacji kogoś innego nie blokował.

**Comment by phoe** [comment]
Nie prościej zrobić wybór w stylu 1234?

1) KSI
2) serwerownia
3) WC
4) winda główna, piętro

**Comment by polarny** [comment]
Na początku chciałem zrobić, żeby można było i tak i tak. Wciąż piję w tą stronę, po prostu jeszcze tego nie zrealizowałem.

Jak wolicie to mogę zrobić po prostu numerki.

**Comment by polarny** [comment]
Zrobione
