### ISSUE TITLE
Nawigacja

### ISSUE THREAD

**Issue by mateuszgwozdz** [KSIUJ/ksicamp-the-game#7]
Jest kilka miejsc poza korytarzem, z których można iść w różne miejsca.
Może by przemieścić implementację nawigacji z korytarza do utilsów,
by dało się z niej korzystać w innych miejscach?

**Comment by phoe** [comment]
Pomysł zacny - miałem to proponować na kolejnym spotkaniu.

Sygnatura, która przychodzi mi na myśl, to `Room choose(std::string query, ...)`, gdzie `...` to varargs przyjmujący serię wartości enuma `Room`. Wywołanie mogłoby wyglądać następująco:

```c++
choose("Kędy stopy twe poniesie?", KSI, SERWEROWNIA, WC, WINDA_PIETRO);
```

(Jeśli ktoś ma lepszy pomysł, niż varargs, to zapraszam do podzielenia się.)

Jedyny nierozwiązany problem to drukowanie nazw enumów - do tego trzeba będzie użyć jakiejś mapy z `Room` do stringów, jak na przykład w https://stackoverflow.com/questions/11714325/how-to-get-enum-item-name-from-its-value

**Comment by polarny** [comment]
W sumie jest jeszcze kwestia tego jak użytkownik ma wybierać te pokoje z listy. 
Na dobry początek można by zrobić przez wpisywanie numerków, bądź coś w tym stylu.
"Kędy stopy twe poniesie?
1) KSI
2) Serwerownia
3) WC
4) Winda Piętro
3"

Jest jeszcze to rozwiązanie zaproponowane na Discordzie ze strzałkami.
"Kędy stopy twe poniesie?
KSI
Serwerownia
->WC
Winda Piętro
"
Jeśli dobrze rozumiem, to by wymagało manipulacji tekstu w konsoli, a takie rzeczy są z kolei (z tego co wyczytałem) specyficzne dla danego systemu operacyjnego. Wydaje mi się, że może to trochę komplikować implementację w zespole, w którym są Maci, Windowsy i Unixy.

**Comment by phoe** [comment]
Numerki są najbardziej przenośne.

**Comment by polarny** [comment]
Nie trzeba nawet mapy, bo wartości Room zadziałają nawet jako indeksy do zwykłej tabeli.

To takie coś mogę w wolnej chwili zaklepać. Zastanawiam się tylko czy nie zostawić to komuś młodszemu.

**Comment by phoe** [comment]
@polarny męcz ludzi na Discordzie, to może ktoś chętny się znajdzie. Przy tym pamiętajmy, żeby nie stawiać poprzeczki zbyt wysoko - zaklepanie *działającego* menu nie jest zadaniem trywialnym dla kogoś pierwszorocznego, jeśli będzie to robił pierwszy raz w życiu.

**Comment by mateuszgwozdz** [comment]
Zgłaszam sieeeeeeeeeee

**Comment by phoe** [comment]
@gwoozdz to pisz

**Comment by mateuszgwozdz** [comment]
@phoe to pisze

**Comment by mateuszgwozdz** [comment]
Do wglądu dostępny jest branch [GPS](https://github.com/KSIUJ/ksicamp-the-game/tree/GPS).

GPS używa się ~~prawie~~ tak jak @phoe proponował:
`gps("Wiadomość", N, ...)`
gdzie _`Wiadomość`_ zostaje wyświotlona użytkownikowi podczas wyboru celu podróży,
_`N`_ jest ilością pomieszczeń (`Room`) do wyboru,
_`...`_ jest odpowiednią listą pomieszczeń (`Room`) oddzielonych przecinkami

Na przykład:
`gps("Dokąd teraz?", 3, KSI, Korytarz, WC);`
spyta użytkownika o wybór i jeśli wszystko pójdzie dobrze, zwróci wybrany przez niego `Room`.

Aby móc używać gps, dołącz jego plik nagłówkowy: `GPS/gps.hpp`.
